### ISSUE TITLE
ASK [hswong3i.jira : create user] ********************************************* fatal: [atlassian.devekko.com]: FAILED! => {"failed": true, "msg": "ERROR! an unexpected type error occurred. Error was crypt() argument 1 must be string, not None"}

### ISSUE THREAD

**Issue by niccolox** [pantarei/ansible-role-jira#2]
hi

trying to install Jira using this role on LXC 2 containers on Trusty and Xenial guests on a Xenial host and get this error on both

ASK [hswong3i.jira : create user] *********************************************
fatal: [atlassian.devekko.com]: FAILED! => {"failed": true, "msg": "ERROR! an unexpected type error occurred. Error was crypt() argument 1 must be string, not None"}

**Comment by niccolox** [comment]
you might want to updated your example playbook

I used this for my play and it seems to run

# jira play
# ansible-playbook jira-play-atlassian-REDACTED-com.yml 

- hosts: atlassian.REDACTED.com
  remote_user: root
  roles:
    - { role: hswong3i.jira, jira_hash_salt: REDACTED, jira_pass: REDACTED, jira_user: jira}

**Comment by hswong3i** [comment]
If you deploy with https://github.com/pantarei/ansible-playbook-jira, this already done during initialization ;-)
