### ISSUE TITLE
Could not find requested service Jira

### ISSUE THREAD

**Issue by jp1987** [pantarei/ansible-role-jira#4]
On an Ubuntu 16.04 machine:

`TASK [hswong3i.jira : enable service] ******************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'jira'\": "}`

`sudo service jira restart` does not work, `sudo /etc/init.d/solr restart` does work.

**Comment by jp1987** [comment]
Hmm, this happened in 2.2.0.0. After upgrading to 2.2.1.0, it works, but gives me this:

`[WARNING]: The service (jira) is actually an init script but the system is
managed by systemd`

**Comment by hswong3i** [comment]
@jp1987 Oops so is issue still happened?

**Comment by jp1987** [comment]
Not on the latest Ansible (except the warning)
